version: "3"

vars:
  TEXASSOLVER_PATH: "{{.TEXASSOLVER_PATH | default (joinPath .PWD \"TexasSolver\")}}"

tasks:
  install:
    desc: 依存関係をインストール (共通)
    cmds:
      - uv sync

  install:linux:
    desc: Linux用依存関係のインストール (sudoが必要)
    cmds:
      - sudo apt update && sudo apt install -y git cmake build-essential pkg-config libevdev-dev obs-studio
      - uv pip install "git+https://github.com/games-on-whales/inputtino.git#subdirectory=bindings/python&branch=stable"
      - uv pip install pamiq-vrchat
      - task install
  fix:
    desc: Lintエラーを自動修正してフォーマット
    cmds:
      - uv run ruff check src tests --fix
      - uv run ruff format src tests
      - uv run pytest -v

  run:
    desc: VRChat Poker GTO システムを起動
    env:
      TEXASSOLVER_PATH: "{{.TEXASSOLVER_PATH}}"
    cmds:
      - uv run vrpoker

  clean:
    desc: ローカルアーティファクトをクリーンアップ
    cmds:
      - rm -rf .venv uv.lock
      - find . -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
      - find . -type d -name ".pytest_cache" -exec rm -rf {} + 2>/dev/null || true
      - find . -type d -name ".ruff_cache" -exec rm -rf {} + 2>/dev/null || true

