version: "3"

vars:
  TEXASSOLVER_PATH: "{{.TEXASSOLVER_PATH | default (joinPath .PWD \"TexasSolver\")}}"

tasks:
  install:
    desc: 依存関係をインストール
    cmds:
      - uv sync

  check:
    desc: Lint、フォーマット、テストを実行
    cmds:
      - uv run ruff check src tests
      - uv run ruff format src tests --check
      - uv run pytest -v

  fix:
    desc: Lintエラーを自動修正してフォーマット
    cmds:
      - uv run ruff check src tests --fix
      - uv run ruff format src tests

  test:
    desc: テストを実行
    cmds:
      - uv run pytest -v

  run:
    desc: VRChat Poker GTO システムを起動
    env:
      TEXASSOLVER_PATH: "{{.TEXASSOLVER_PATH}}"
    cmds:
      - uv run vrpoker

  clean:
    desc: ローカルアーティファクトをクリーンアップ
    cmds:
      - rm -rf .venv uv.lock
      - find . -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
      - find . -type d -name ".pytest_cache" -exec rm -rf {} + 2>/dev/null || true
      - find . -type d -name ".ruff_cache" -exec rm -rf {} + 2>/dev/null || true

